### ISSUE TITLE
Step Option UI is incorrect from yaml

### ISSUE THREAD

**Issue by Soulphalanx** [bitrise-io/steps-xcode-archive#109]
The field for bitcode is being displayed as force development team

This is what I see in the step options:
<img width="1317" alt="image" src="https://user-images.githubusercontent.com/1175706/39734679-3a01637a-522d-11e8-80d9-76f551a47b4a.png">

If I delete the value for `Force codesigning with Development team`, I get an error when running the step: `Issue with input: issue with input UploadBitcode: parameter not specified`

This is what it actually is in the yaml
```
    - xcode-archive:
        inputs:
        - export_method: app-store
        - is_export_xcarchive_zip: 'yes'
        - configuration: Release
        - artifact_name: "$BITRISE_SCHEME"
        - xcodebuild_options: "-sdk iphoneos"
        - is_clean_build: 'yes'
        - upload_bitcode: 'yes'
        - team_id: BAUE6Z43LF
```
