### ISSUE TITLE
no scheme found with name: X in workspace: X in version 2.4.16 

### ISSUE THREAD

**Issue by v3n3** [bitrise-io/steps-xcode-archive#135]
Hi, 

i use the xcode-archive `2.4.16` with the following setting:
```yml
- xcode-archive:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
        - xcodebuild_options: "-allowProvisioningUpdates -UseModernBuildSystem=NO"
        - configuration: Beta
        - export_method: ad-hoc
```
the step automatically throws the following error:
```
Exporting ipa from the archive...

Exporting ipa with ExportOptions.plist
No custom export options content provided, generating export options...
export-method specified: ad-hoc
no scheme found with name: XX in workspace: XX.xcworkspace
```

However, if i use version `2.4.15` the step is properly executed. Is it a bug or am i missing some configuration?
