### ISSUE TITLE
Expose location of .app folder.

### ISSUE THREAD

**Issue by castillobg** [bitrise-io/steps-xcode-archive#32]
The `.app` folder is needed sometimes by other services like Saucelabs to run acceptance tests. It'd be great if this step generated an output variable with the path to it. :smile:

**Comment by castillobg** [comment]
so,  running some debug echos on the build, and based on [this line](https://github.com/bitrise-io/steps-xcode-archive/blob/e8cdd40710cf159a36c522539c86814742926263/step.sh#L254)
I think this could be done like this:
`envman add --key BITRISE_APP_PATH --value $(find "${archive_path}/Products/Applications" -type d -name '*.app')`
And adding the output var in step.yml

step.yml:
```
...
outputs:
  - BITRISE_IPA_PATH:
    opts:
      title: The created .ipa file's path
  - BITRISE_DSYM_PATH:
    opts:
      title: The created .dSYM.zip file's path
  - BITRISE_APP_PATH:
     opts:
       title: The generated .app directory path
  - BITRISE_XCARCHIVE_PATH:
    opts:
      title: The created .xcarchive.zip file's path
```
