### ISSUE TITLE
Automatic code signing not working for cordova generated projects

### ISSUE THREAD

**Issue by patrickbussmann** [bitrise-io/steps-xcode-archive#54]
After I read the answer of @viktorbenei I tested around some settings. https://github.com/bitrise-io/steps-xcode-archive/issues/53#issuecomment-254035694

The problem here is that the automatic signing does not work and so my build process fails each time. http://blog.bitrise.io/2016/09/21/xcode-8-and-automatic-code-signing.html

Here are the error messages with the xcode-archive configuration.

If I build something via xCode I'm disabling the "automatically manage signing" and selecting an AdHoc provisioning profile.

Because I'm using a cordova generated xCode project the default settings of the project are the default development profile.

Thanks in Advance for ideas.
#### TestApp has conflicting provisioning settings. TestApp is automatically signed for development, but a conflicting code signing identity iPhone Distribution has been manually specified. Set the code signing identity value to "iPhone Developer" in the build settings editor, or switch to manual signing in the project editor. Code signing is required for product type 'Application' in SDK 'iOS 10.1'

```
- xcode-archive:
    title: TestApp xCode Archive for iOS
    inputs:
    - workdir: "$BITRISE_SOURCE_DIR/platforms/ios"
    - project_path: "$BITRISE_SOURCE_DIR/platforms/ios/TestApp.xcodeproj"
    - scheme: TestApp
    - force_team_id: AY2H9C3YC1
    - force_code_sign_identity: ''
    - output_tool: xcodebuild
    - is_export_xcarchive_zip: 'yes'
    - custom_export_options_plist_content: ad-hoc
```
#### Signing for "TestApp" requires a development team. Select a development team in the project editor. Code signing is required for product type 'Application' in SDK 'iOS 10.1'

```
- xcode-archive:
    title: TestApp xCode Archive for iOS
    inputs:
    - workdir: "$BITRISE_SOURCE_DIR/platforms/ios"
    - project_path: "$BITRISE_SOURCE_DIR/platforms/ios/TestApp.xcodeproj"
    - scheme: TestApp
    - force_team_id: ''
    - force_code_sign_identity: ''
    - output_tool: xcodebuild
    - is_export_xcarchive_zip: 'yes'
    - custom_export_options_plist_content: ad-hoc
```
#### Signing for "TestApp" requires a development team. Select a development team in the project editor. Code signing is required for product type 'Application' in SDK 'iOS 10.1'

```
- xcode-archive:
    title: TestApp xCode Archive for iOS
    inputs:
    - workdir: "$BITRISE_SOURCE_DIR/platforms/ios"
    - project_path: "$BITRISE_SOURCE_DIR/platforms/ios/TestApp.xcodeproj"
    - scheme: TestApp
    - force_team_id: ''
    - force_code_sign_identity: ''
    - force_provisioning_profile: b284373b-9b5f-4e01-9af0-6442b6bb5222
    - output_tool: xcodebuild
    - is_export_xcarchive_zip: 'yes'
    - custom_export_options_plist_content: ad-hoc
```
#### Signing for "TestApp" requires a development team. Select a development team in the project editor. Code signing is required for product type 'Application' in SDK 'iOS 10.1'

```
- xcode-archive:
    title: TestApp xCode Archive for iOS
    inputs:
    - workdir: "$BITRISE_SOURCE_DIR/platforms/ios"
    - project_path: "$BITRISE_SOURCE_DIR/platforms/ios/TestApp.xcodeproj"
    - output_tool: xcodebuild
    - is_export_xcarchive_zip: 'yes'
    - custom_export_options_plist_content: ad-hoc
```
